// DO NOT EDIT THIS FILE DIRECTLY! Go to the Crowdin project website to translate it: https://crowdin.com/project/kirakira


export default {
	SendRegistrationVerificationCode: {},
	SendChangeEmailVerificationCode: {},
	SendChangePasswordVerificationCode: {},
	SendResetPasswordVerificationCode: {},
	SendLoginVerificationCode: {},
	SendDisableUserEmail2FAVerificationCode: {},
	SendGeneral2FAEmailVerificationCode: {},
	SendGeneralEmailVerificationCode: {},
}
