// DO NOT EDIT THIS FILE DIRECTLY! Go to the Crowdin project website to translate it: https://crowdin.com/project/kirakira


export default {
	SendVerificationCode: {
		mailTitle: "KIRAKIRA - 注册验证码",
		mailHeading: "你的注册验证码是",
		mailText: "欢迎来到KIRAKIRA，使用这个验证码来注册你的账号吧！\n验证码30分钟内有效。请注意安全，不要向他人泄露你的验证码。\n要停止接收通知，请联系KIRAKIRA支持团队。",
	},
	SendChangeEmailVerificationCode: {
		mailTitle: "KIRAKIRA - 更改邮箱验证码",
		mailHeading: "你更改邮箱的验证码是",
		mailText: "验证码30分钟内有效。请注意安全，不要向他人泄露你的验证码。\n要停止接收通知，请联系KIRAKIRA支持团队。",
	},
	SendChangePasswordVerificationCode: {
		mailTitle: "KIRAKIRA - 更改密码验证码",
		mailHeading: "你更改密码的验证码是",
		mailText: "验证码30分钟内有效。请注意安全，不要向他人泄露你的验证码。\n要停止接收通知，请联系KIRAKIRA支持团队。",
	},
	SendResetPasswordVerificationCode: {
		mailTitle: "KIRAKIRA - 找回密码验证码",
		mailHeading: "你找回密码的验证码是",
		mailText: "验证码30分钟内有效。请注意安全，不要向他人泄露你的验证码。\n要停止接收通知，请联系KIRAKIRA支持团队。",
	},
	SendLoginVerificationCode: {
		mailTitle: "KIRAKIRA - 登录验证码",
		mailHeading: "你的登录验证码是",
		mailText: "验证码30分钟内有效。请注意安全，不要向他人泄露你的验证码。\n要停止接收通知，请联系KIRAKIRA支持团队。",
	},
	SendDisableUserEmail2FAVerificationCode: {
		mailTitle: "KIRAKIRA - 禁用邮箱双重验证验证码",
		mailHeading: "你的验证码是",
		mailText: "验证码30分钟内有效。请注意安全，不要向他人泄露你的验证码。\n要停止接收通知，请联系KIRAKIRA支持团队。",
	},
}
