// DO NOT EDIT THIS FILE DIRECTLY! Go to the Crowdin project website to translate it: https://crowdin.com/project/kirakira


export default {
	SendVerificationCode: {
		mailTitle: "KIRAKIRA - Code de vérification d'enregistrement",
		mailHeading: "Votre code de vérification d'inscription est",
		mailText: "Bienvenue sur KIRAKIRA. Vous pouvez utiliser ce code de vérification pour enregistrer votre compte.\nLe code de vérification est valide pendant 30 minutes. Veuillez vous assurer de ne pas divulguer votre code de vérification à d'autres.\nPour ne plus recevoir de notifications, veuillez contacter l'équipe d'assistance de KIRAKIRA.",
	},
	SendChangeEmailVerificationCode: {
		mailTitle: "KIRAKIRA - Changer le code de vérification d'email",
		mailHeading: "Votre code de vérification de courriel de changement est",
		mailText: "Le code de vérification est valable 30 minutes. Veuillez ne pas le divulguer à d'autres personnes.\nPour ne plus recevoir de notifications, veuillez contacter l'équipe d'assistance de KIRAKIRA.",
	},
	SendChangePasswordVerificationCode: {
		mailTitle: "KIRAKIRA - Changer le code de vérification du mot de passe",
		mailHeading: "Votre code de vérification de mot de passe de changement est",
		mailText: "Le code de vérification est valable 30 minutes. Veuillez ne pas le divulguer à d'autres personnes.\nPour ne plus recevoir de notifications, veuillez contacter l'équipe d'assistance de KIRAKIRA.",
	},
	UserEmailAuthenticator: {
		mailTitle: "KIRAKIRA - Code de vérification pour la vérification de 2FA",
		mailHeading: "Votre code de vérification pour la vérification de l'authentificateur est",
		mailText: "Remarque : Veuillez vous assurer que vous utiliserez ce code de vérification pour vérifier votre authentificateur.\nLe code de vérification est valide pendant 30 minutes. Veuillez vous assurer de ne pas divulguer votre code de vérification à d'autres.\nPour ne plus recevoir de notifications, veuillez contacter l'équipe d'assistance de KIRAKIRA.",
	},
	DeleteUserEmailAuthenticator: {
		mailTitle: "KIRAKIRA - Code de vérification pour la suppression de 2FA",
		mailHeading: "Votre code de vérification pour la suppression de l'authentificateur est",
		mailText: "Remarque : Veuillez vous assurer que vous utiliserez ce code de vérification pour supprimer votre authentificateur.\nLe code de vérification est valide pendant 30 minutes. Veuillez vous assurer de ne pas divulguer votre code de vérification à d'autres.\nPour ne plus recevoir de notifications, veuillez contacter l'équipe d'assistance de KIRAKIRA.",
	},
}
