// DO NOT EDIT THIS FILE DIRECTLY! Go to the Crowdin project website to translate it: https://crowdin.com/project/kirakira


export default {
	SendRegistrationVerificationCode: {
		mailTitle: "KIRAKIRA-登録用認証コード",
		mailHeading: "登録用確認のコードは",
		mailText: "KIRAKIRA へようこそ！このコードを使ってアカウント登録を完了しましょう。\nコードの有効期間は 30 分です。このコードは他の人には絶対に教えないでください。\n通知の受信を停止するには、KIRAKIRA サポートチームまでご連絡ください。",
	},
	SendChangeEmailVerificationCode: {
		mailTitle: "KIRAKIRA - メールアドレス変更の確認コード",
		mailHeading: "メールアドレスの確認コードは",
		mailText: "確認コードの有効期間は 30 分です。このコードは他の人には絶対に教えないでください。\n通知の受信を停止するには、KIRAKIRA サポートチームまでご連絡ください。",
	},
	SendChangePasswordVerificationCode: {
		mailTitle: "KIRAKIRA - パスワード変更の認証コード",
		mailHeading: "パスワード変更の確認コードは",
		mailText: "確認コードの有効期間は 30 分です。このコードは他の人には絶対に教えないでください。\n通知の受信を停止するには、KIRAKIRA サポートチームまでご連絡ください。",
	},
	SendResetPasswordVerificationCode: {
		mailTitle: "KIRAKira - パスワードリセット用認証コード",
		mailHeading: "パスワードリセット用のコードは",
		mailText: "確認コードの有効期間は 30 分です。このコードは他の人には絶対に教えないでください。\n通知の受信を停止するには、KIRAKIRA サポートチームまでご連絡ください。",
	},
	SendLoginVerificationCode: {
		mailTitle: "KIRAKIA - ログイン認証コード",
		mailHeading: "ログイン認証コードは",
		mailText: "確認コードの有効期間は 30 分です。このコードは他の人には絶対に教えないでください。\n通知の受信を停止するには、KIRAKIRA サポートチームまでご連絡ください。",
	},
	SendDisableUserEmail2FAVerificationCode: {
		mailTitle: "KIRAKira - メール2FA認証コードを無効にする",
		mailHeading: "認証コードは",
		mailText: "確認コードの有効期間は 30 分です。このコードは他の人には絶対に教えないでください。\n通知の受信を停止するには、KIRAKIRA サポートチームまでご連絡ください。",
	},
}
