// DO NOT EDIT THIS FILE DIRECTLY! Go to the Crowdin project website to translate it: https://crowdin.com/project/kirakira


export default {
	SendVerificationCode: {},
	SendChangeEmailVerificationCode: {},
	SendChangePasswordVerificationCode: {},
	SendResetPasswordVerificationCode: {},
	SendLoginVerificationCode: {},
	SendDisableUserEmail2FAVerificationCode: {},
}
