// DO NOT EDIT THIS FILE DIRECTLY! Go to the Crowdin project website to translate it: https://crowdin.com/project/kirakira


export default {
	SendRegistrationVerificationCode: {
		mailTitle: "crwdns3786:0crwdne3786:0",
		mailHeading: "crwdns3788:0crwdne3788:0",
		mailText: "crwdns3790:0crwdne3790:0",
	},
	SendChangeEmailVerificationCode: {
		mailTitle: "crwdns3161:0crwdne3161:0",
		mailHeading: "crwdns3163:0crwdne3163:0",
		mailText: "crwdns3165:0crwdne3165:0",
	},
	SendChangePasswordVerificationCode: {
		mailTitle: "crwdns3167:0crwdne3167:0",
		mailHeading: "crwdns3169:0crwdne3169:0",
		mailText: "crwdns3171:0crwdne3171:0",
	},
	SendResetPasswordVerificationCode: {
		mailTitle: "crwdns3692:0crwdne3692:0",
		mailHeading: "crwdns3694:0crwdne3694:0",
		mailText: "crwdns3696:0crwdne3696:0",
	},
	SendLoginVerificationCode: {
		mailTitle: "crwdns3622:0crwdne3622:0",
		mailHeading: "crwdns3624:0crwdne3624:0",
		mailText: "crwdns3626:0crwdne3626:0",
	},
	SendDisableUserEmail2FAVerificationCode: {
		mailTitle: "crwdns3628:0crwdne3628:0",
		mailHeading: "crwdns3630:0crwdne3630:0",
		mailText: "crwdns3632:0crwdne3632:0",
	},
	SendGeneral2FAEmailVerificationCode: {
		mailTitle: "crwdns3816:0crwdne3816:0",
		mailHeading: "crwdns3818:0crwdne3818:0",
		mailText: "crwdns3820:0crwdne3820:0",
	},
	SendGeneralEmailVerificationCode: {
		mailTitle: "crwdns3822:0crwdne3822:0",
		mailHeading: "crwdns3824:0crwdne3824:0",
		mailText: "crwdns3826:0crwdne3826:0",
	},
}
