// DO NOT EDIT THIS FILE DIRECTLY! Go to the Crowdin project website to translate it: https://crowdin.com/project/kirakira


export default {
	SendVerificationCode: {
		mailTitle: "crwdns3155:0crwdne3155:0",
		mailHeading: "crwdns3157:0crwdne3157:0",
		mailText: "crwdns3159:0crwdne3159:0",
	},
	SendChangeEmailVerificationCode: {
		mailTitle: "crwdns3161:0crwdne3161:0",
		mailHeading: "crwdns3163:0crwdne3163:0",
		mailText: "crwdns3165:0crwdne3165:0",
	},
	SendChangePasswordVerificationCode: {
		mailTitle: "crwdns3167:0crwdne3167:0",
		mailHeading: "crwdns3169:0crwdne3169:0",
		mailText: "crwdns3171:0crwdne3171:0",
	},
	UserEmailAuthenticator: {
		mailTitle: "crwdns3173:0crwdne3173:0",
		mailHeading: "crwdns3175:0crwdne3175:0",
		mailText: "crwdns3177:0crwdne3177:0",
	},
	DeleteUserEmailAuthenticator: {
		mailTitle: "crwdns3179:0crwdne3179:0",
		mailHeading: "crwdns3181:0crwdne3181:0",
		mailText: "crwdns3183:0crwdne3183:0",
	},
}
