// DO NOT EDIT THIS FILE DIRECTLY! Go to the Crowdin project website to translate it: https://crowdin.com/project/kirakira


export default {
	SendVerificationCode: {
		mailTitle: "crwdns3620:0crwdne3620:0",
		mailHeading: "crwdns3157:0crwdne3157:0",
		mailText: "crwdns3159:0crwdne3159:0",
	},
	SendChangeEmailVerificationCode: {
		mailTitle: "crwdns3161:0crwdne3161:0",
		mailHeading: "crwdns3163:0crwdne3163:0",
		mailText: "crwdns3165:0crwdne3165:0",
	},
	SendChangePasswordVerificationCode: {
		mailTitle: "crwdns3167:0crwdne3167:0",
		mailHeading: "crwdns3169:0crwdne3169:0",
		mailText: "crwdns3171:0crwdne3171:0",
	},
	SendResetPasswordVerificationCode: {
		mailTitle: "crwdns3692:0crwdne3692:0",
		mailHeading: "crwdns3694:0crwdne3694:0",
		mailText: "crwdns3696:0crwdne3696:0",
	},
	SendLoginVerificationCode: {
		mailTitle: "crwdns3622:0crwdne3622:0",
		mailHeading: "crwdns3624:0crwdne3624:0",
		mailText: "crwdns3626:0crwdne3626:0",
	},
	SendDisableUserEmail2FAVerificationCode: {
		mailTitle: "crwdns3628:0crwdne3628:0",
		mailHeading: "crwdns3630:0crwdne3630:0",
		mailText: "crwdns3632:0crwdne3632:0",
	},
}
