// DO NOT EDIT THIS FILE DIRECTLY! Go to the Crowdin project website to translate it: https://crowdin.com/project/kirakira


export default {
	SendVerificationCode: {
		mailTitle: "KIRAKIRA - Mã Xác Minh Đăng Ký",
		mailHeading: "Mã xác minh đăng ký của bạn là",
		mailText: "Chào mừng đến với KIRAKIRA. Bạn có thể sử dụng mã xác minh này để đăng ký tài khoản của mình.\nMã xác minh có hiệu lực trong 30 phút. Vui lòng đảm bảo không tiết lộ mã xác minh của bạn cho người khác.\nĐể ngừng nhận thông báo, vui lòng liên hệ với nhóm hỗ trợ KIRAKIRA.",
	},
	SendChangeEmailVerificationCode: {
		mailTitle: "KIRAKIRA - Mã Xác Minh Đổi Email",
		mailHeading: "Mã xác minh đổi email của bạn là",
		mailText: "Mã xác minh có hiệu lực trong 30 phút. Vui lòng đảm bảo không tiết lộ mã xác minh của bạn cho người khác.\nĐể ngừng nhận thông báo, vui lòng liên hệ với nhóm hỗ trợ KIRAKIRA.",
	},
	SendChangePasswordVerificationCode: {
		mailTitle: "KIRAKIRA - Mã Xác Minh Đổi Mật Khẩu",
		mailHeading: "Mã xác minh đổi mật khẩu của bạn là",
		mailText: "Mã xác minh có hiệu lực trong 30 phút. Vui lòng đảm bảo không tiết lộ mã xác minh của bạn cho người khác.\nĐể ngừng nhận thông báo, vui lòng liên hệ với nhóm hỗ trợ KIRAKIRA.",
	},
	UserEmailAuthenticator: {
		mailTitle: "KIRAKIRA - Mã Xác Minh Dành Cho Xác Thực 2 Bước",
		mailHeading: "Mã xác minh của bạn để xác thực Authenticator là",
		mailText: "Lưu ý: Vui lòng đảm bảo bạn sẽ sử dụng mã xác minh này để xác minh Authenticator của mình.\nMã xác minh có hiệu lực trong 30 phút. Vui lòng đảm bảo không tiết lộ mã xác minh của bạn cho người khác.\nĐể ngừng nhận thông báo, vui lòng liên hệ với nhóm hỗ trợ KIRAKIRA.",
	},
	DeleteUserEmailAuthenticator: {
		mailTitle: "KIRAKIRA - Mã Xác Minh Gỡ Bỏ Xác Thực 2 Bước",
		mailHeading: "Mã xác minh của bạn để xóa Authenticator là",
		mailText: "Lưu ý: Vui lòng đảm bảo bạn sẽ sử dụng mã xác minh này để xóa Authenticator của mình.\nMã xác minh có hiệu lực trong 30 phút. Vui lòng đảm bảo không tiết lộ mã xác minh của bạn cho người khác.\nĐể ngừng nhận thông báo, vui lòng liên hệ với nhóm hỗ trợ KIRAKIRA.",
	},
}
